#!name=吾爱破解
#!desc=吾爱破解 Cookie获取(浏览器打开 https://www.52pojie.cn/home.php 登录账号)
#!author=taylor
#!homepage=https://github.com/Yuheng0101/X

[rewrite_local]
^https:\/\/www\.52pojie\.cn\/home\.php\? url script-request-header https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/52pojie.js

[task_local]
0 9 * * * https://raw.githubusercontent.com/Yuheng0101/X/main/Tasks/52pojie.js, tag=吾爱破解签到, img-url=https://raw.githubusercontent.com/Yuheng0101/X/main/Assets/52pojie.png, enabled=true

[mitm]
hostname = www.52pojie.cn