#!name=CamScanner Cookie
#!desc=「扫描全能王」APP 任意页面停留几秒
#!author=taylor

[rewrite_local]
^https:\/\/api-cs\.intsig\.net\/user\/cs\/get_user_attribute url script-request-header https://raw.githubusercontent.com/MaYIHEI/paperclip/refs/heads/main/app/camscanner/camscanner.cookie.js

[MITM]
hostname = api-cs.intsig.net