#!name=海底捞小程序 Token
#!desc=打开微信小程序「海底捞」→ 进入「我的」→ 任意签到入口,触发签到接口
#!author=taylor

[rewrite_local]
^https:\/\/superapp-public\.kiwa-tech\.com\/activity\/wxapp\/signin\/(query|querySite|querySwitch|queryFragment|signin) url script-request-header https://raw.githubusercontent.com/MaYIHEI/paperclip/refs/heads/main/miniprogram/haidilao/haidilao.js

[MITM]
hostname = superapp-public.kiwa-tech.com