#!name=龙湖天街 Token
#!desc=微信小程序「龙湖天街」→ 底部「会员」→「日日签 日日赚」→ 点击签到按钮一次
#!author=taylor

[rewrite_local]
^https:\/\/gw2c-hw-open\.longfor\.com\/lmarketing-task-api-mvc-prod\/openapi\/task\/v1\/signature\/clock$ url script-request-header https://raw.githubusercontent.com/MaYIHEI/paperclip/refs/heads/main/miniprogram/lhtj/lhtj.js

[MITM]
hostname = gw2c-hw-open.longfor.com

[task_local]
0 9 * * * https://raw.githubusercontent.com/MaYIHEI/paperclip/refs/heads/main/miniprogram/lhtj/lhtj.js, tag=龙湖天街签到, img-url=https://raw.githubusercontent.com/leiyiyan/resource/main/icons/lhtj.png, enabled=true