#!name=Apple Location Spoofer
#!desc=Apple 定位伪装及 BoxJS 数据写入
#!author=taylor

[MITM]
hostname = gs-loc-cn.apple.com, gs-loc.apple.com, boxjs.my

[Rewrite]
^https?:\/\/(gs-loc-cn|gs-loc)\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/id77/QuantumultX/master/Script/wloc_spoofer.js
^https:\/\/boxjs\.my\/write url script-analyze-echo-response https://raw.githubusercontent.com/id77/QuantumultX/master/Script/write_data.js