#!name=小米抽奖签到 Cookie
#!desc=打开小米商城 APP →「狂欢礼」→ 进入抽奖活动页
#!author=taylor

[rewrite_local]
^https://shop-api.retail.mi.com/mtop/navi/venue/batch url script-request-body https://raw.githubusercontent.com/MaYIHEI/paperclip/refs/heads/main/app/milottery/milottery.js

[task_local]
30 8 * * * https://raw.githubusercontent.com/MaYIHEI/paperclip/refs/heads/main/app/milottery/milottery.js, tag=小米抽奖签到, img-url=https://raw.githubusercontent.com/MaYIHEI/pin/refs/heads/main/app/mishop.png, enabled=true

[MITM]
hostname = shop-api.retail.mi.com
