#!name=小米活动Cookie（抓取:打开小米商城 APP → 首页「米金商城」→ 点签到,触发 do/done 抓 cookie + userId + headers）
#!desc=获取小米活动接口请求头Cookie
#!author=taylor

[rewrite_local]
^https:\/\/shop-api\.retail\.mi\.com\/mtop\/mf\/act\/infinite\/(do|done) url script-request-header https://raw.githubusercontent.com/MaYIHEI/paperclip/refs/heads/main/app/mishop/mishop.cookie.js

[MITM]
hostname = shop-api.retail.mi.com