#!name=国家电网 Cookie
#!desc=打开「网上国网」App → 进「我的 / 积分签到」页,抓 Cookie(t/设备头)+ 签到请求(供 cron 复用)
#!author=taylor

[rewrite_local]
^https?:\/\/csc-service\.sgcc\.com\.cn:28630\/.+\/member\/ url script-request-body https://raw.githubusercontent.com/MaYIHEI/paperclip/refs/heads/main/app/sgcc/sgcc.cookie.js

[MITM]
hostname = csc-service.sgcc.com.cn